### ISSUE TITLE
Can I Prevent showing the "Do you want to allow this page to open “Stop The Mac App Store.app”?

### ISSUE THREAD

**Issue by yoasha** [lapcat/StopTheMacAppStore#1]
Great app thank you! 
There is still some annoyance of getting the message "Do you want to allow this page to open...” each time I am browsing to iOS app URL. Is there any way to completely silent this message? 
BTW, I'm obj-c programmer, so I can modify the code if needed.

**Comment by lapcat** [comment]
> getting the message "Do you want to allow this page to open...” each time I am browsing to iOS app URL

Do you mean iOS app URL or Mac app URL? I'm not seeing the dialog for iOS apps.

In general, the dialog cannot be stopped, because the dialog is the only thing that stops the App Store app from opening.

**Comment by yoasha** [comment]
Yes, I refer to iOS apps. This issue seems to happen with iOS apps that are also available on the Mac App Store (for example, if the developer allowed it to run on M1 Macs) or with macOS apps.
For example:
bookly iOS app - https://apps.apple.com/us/app/bookly-track-books-stats/id1085047737
Apple Numbers Mac app - https://apps.apple.com/us/app/numbers/id409203825?ls=1&mt=12&v0=www-us-mac-numbers-app-numbers

With your app I get the message which is much better than the App Store app, but I wish there was a way to silent it entirely.

**Comment by lapcat** [comment]
Thanks for the clarification.

Unfortunately, StopTheMacAppStore can't do anything to prevent the dialog. The app doesn't actually do anything inside Safari, it just sets itself as the default handler for App Store URLs on your Mac.
