### ISSUE TITLE
Can't see the App Store pages in Safari in many cases

### ISSUE THREAD

**Issue by Tekl** [lapcat/StopTheMacAppStore#3]
When I open Links [apps.apple.com/de/app/id1508706541](https://apps.apple.com/de/app/id1508706541) I only see the App Store Logo in Safari with the text "Connecting ...". So Stop The Mac App Store is not very helpful in this case. Sporadically, I will see the pages when I don't allow opening the App Store App, but in many cases not.

**Comment by lapcat** [comment]
That app is not currently available in the Mac App Store.

This has nothing to do with Stop The Mac App Store. It doesn't change what is displayed in your web browser. You would see the same thing if you uninstalled the app.

**Comment by Tekl** [comment]
Ah thanks. Didn't realize that I tested an old link. 🤦
