### ISSUE TITLE
Accidentally clicked on Always Allow

### ISSUE THREAD

**Issue by diogocampos** [lapcat/StopTheMacAppStore#7]
I opened an App Store page in Safari and accidentally clicked on "Always Allow". 🤦

Now the App Store always opens and the dialog box isn't showing anymore. Is there a way to restore the previous behavior?

**Comment by lapcat** [comment]
Yes, see my blog post: https://lapcatsoftware.com/articles/2023/10/6.html

**Comment by diogocampos** [comment]
> Yes, see my blog post: https://lapcatsoftware.com/articles/2023/10/6.html

That fixed it, thanks!
